apiVersion: v1
kind: Service
metadata:
  name: locust
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8089
      nodePort: 30089
  selector:
    app: locust